app.db.url=jdbc:mysql://cardb:3306/car
app.db.user=mmpataki
app.db.password=test@123
app.db.driver=com.mysql.jdbc.Driver

searchservice.solr.url=http://localhost:8983/solr/car
index.store.class=car.engine.store.SolrStore

emailservice.sender.email.id=mpataki@test.com
emailservice.auth.enabled=false
emailservice.ssl.enabled=false
emailservice.smtp.host=mail.test.com
emailservice.smtp.port=25
emailservice.smtp.trust=mail.test.com

storageservice.root.dir=files

adminservice.trusted.doc.dir=./trusteddata
adminservice.backup.dir=./backup

vcservice.storage.dir=./vcs

store.class=car.engine.store.MySqlStore
store.mysqlstore.url=jdbc:mysql://cardb:3306
store.mysqlstore.user=mmpataki
store.mysqlstore.password=test@123

deployment.master.url=http://car-app:9091
deployment.am.i.master=true

processor.threadpool.size=5

maxMsgsToProcess=-1

app.processing.engine.class=car.processing.engine.SdfsClusterProcessor

sdfs.clusterprocessor.headnode.host=localhost
sdfs.clusterprocessor.headnode.port=5001
sdfs.clusterprocessor.block..size=67108864

nnhost=localhost
nnport=5001

car.app.url=http://car-app:8080

fs.class=car.fs.CarSDFileSystem
sdfs.headnode.host=localhost
sdfs.headnode.port=5001
sdfs.block.size=67108864
