spring.http.converters.preferred-json-mapper=gson
spring.http.multipart.max-file-size=50MB
spring.http.multipart.max-request-size=50MB
server.error.whitelabel.enabled=false
spring.resources.add-mappings=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.mvc.converters.preferred-json-mapper=gson
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
